version: 1.0.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  authors: Brian Greco
  licenseUrl: http://www.opensource.org/licenses/mit-license.php
  projectUrl: https://github.com/grecosoft/NetFusion
  tags: plugin plug-in module autofac mef
before_build:
- cmd: nuget.exe restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: c/FNue2mw27B5A0B1V+pAtSl22XoSqSMu6pj8xIlKGdwAEqoCq7HRxtTqsJl/m1L
  skip_symbols: false
  artifact: /.*\.nupkg/