version: 1.4.{build}
image: Previous Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

before_build:
  - ps: dotnet restore 

build_script:
  - ps: dotnet build --version-suffix %APPVEYOR_BUILD_NUMBER%
  
test_script:
  - ps: dotnet test .\test\CommonTests\CommonTests.csproj
  - ps: dotnet test .\test\CoreTests\CoreTests.csproj
  - ps: dotnet test .\test\DomainTests\DomainTests.csproj
  - ps: dotnet test .\test\InfrastructureTests\InfrastructureTests.csproj
  - ps: dotnet test .\test\IntegrationTests\IntegrationTests.csproj
  - ps: dotnet test .\test\UtilitiesTests\UtilitiesTests.csproj
  
after_build:
	  - dotnet pack .\src\Common\NetFusion.Common\NetFusion.Common.csproj