version: 1.4.{build}
image: Previous Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

before_build:
  - ps: dotnet restore 

build:
  project: NetFusion.sln
  verbosity: minimal
  
test_script:
  - ps: dotnet test .\test\CommonTests\CommonTests.csproj
  - ps: dotnet test .\test\CoreTests\CoreTests.csproj
  