version: 1.4.{build}
image: Previous Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

before_build:
  - ps: dotnet restore 

build:
  project: NetFusion.sln
  verbosity: minimal
  
test_script:
  - ps: dotnet test .\test\CommonTests\CommonTests.csproj
  - ps: dotnet test .\test\CoreTests\CoreTests.csproj
  - ps: dotnet test .\test\DomainTests\DomainTests.csproj
  - ps: dotnet test .\test\InfrastructureTests\InfrastructureTests.csproj
  - ps: dotnet test .\test\IntegrationTests\IntegrationTests.csproj
  - ps: dotnet test .\test\UtilitiesTests\UtilitiesTests.csproj
  
after_build:
  - ps: dotnet pack .\src\Common\NetFusion.Common\NetFusion.Common.csproj /p:VersionPrefix="$env:APPVEYOR_BUILD_VERSION"
  
artifacts:
  - path: src\**\*.nupkg
    name: MyGet
  
deploy:
  - provider: NuGet
    artifact: MyGet
    api_key:
      secure: c/FNue2mw27B5A0B1V+pAtSl22XoSqSMu6pj8xIlKGdwAEqoCq7HRxtTqsJl/m1L
    skip_symbols: false
  