version: 1.6.{build}
image: Previous Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

before_build:
  - ps: dotnet restore 

build_script:
  - ps: dotnet build .\NetFusion.sln /p:VersionPrefix="$env:APPVEYOR_BUILD_VERSION"
  
after_build:
  - ps: dotnet pack /p:VersionPrefix="$env:APPVEYOR_BUILD_VERSION" .\src\Common\NetFusion.Base\NetFusion.Base.csproj 
  - ps: dotnet pack  /p:VersionPrefix="$env:APPVEYOR_BUILD_VERSION"  .\src\Common\NetFusion.Common\NetFusion.Common.csproj
    
artifacts:
  - path: src\**\*.nupkg
    name: MyGet
  